/*
 * generated by Xtext
 */
package edu.tadp.firewall.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class FirewalllUiModule extends edu.tadp.firewall.ui.AbstractFirewalllUiModule {
	public FirewalllUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
