/*
* generated by Xtext
*/
package edu.tadp.firewall.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import edu.tadp.firewall.services.FirewalllGrammarAccess;

public class FirewalllParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private FirewalllGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected edu.tadp.firewall.parser.antlr.internal.InternalFirewalllParser createParser(XtextTokenStream stream) {
		return new edu.tadp.firewall.parser.antlr.internal.InternalFirewalllParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Firewall";
	}
	
	public FirewalllGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(FirewalllGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
