/*
* generated by Xtext
*/
package edu.tadp.firewall;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class FirewalllUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return edu.tadp.firewall.ui.internal.FirewalllActivator.getInstance().getInjector("edu.tadp.firewall.Firewalll");
	}
	
}
