/*
 * generated by Xtext
 */
package edu.tadp.firewall.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import edu.tadp.firewall.ui.internal.FirewalllActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class FirewalllExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FirewalllActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return FirewalllActivator.getInstance().getInjector(FirewalllActivator.EDU_TADP_FIREWALL_FIREWALLL);
	}
	
}
