/*
* generated by Xtext
*/
package edu.tadp.firewall.ui.contentassist;

import edu.tadp.firewall.ui.contentassist.AbstractFirewalllProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class FirewalllProposalProvider extends AbstractFirewalllProposalProvider {

}
