/*
 * generated by Xtext
 */
package edu.tadp.firewall;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class FirewalllRuntimeModule extends edu.tadp.firewall.AbstractFirewalllRuntimeModule {

}
